* 关于　己所不欲　勿施于人　在现在社会还会被认同吗?

  一直以来　我一直都认同这个观点，这也算是自己的人生观。自己也从来没有想过这个观点会在昨天受到了冲击。
起因是我以前说过我媳妇她对自己和对我老搞双重标准。然后某一天她告诉我 她对人是双重标准 对自己比较宽松，对我就比较严格。她说她也疑惑过，所以专门去找同事问了问。
结果她同事说他也这样。(⊙﹏⊙)b。 回家后就开始说为啥她是这双重标准并且这是在适应这个社会。
难道 **己所不欲勿施于人** 真的就过时了，我落伍了？！ 

  so, 俗话说内事不决问度娘。/己所不欲勿施于人 过时吗了/ 发现其实结果并不多。看来大家都不太迷惑这个话题。
但是也看到了一篇好文 [[ http://www.360doc.com/content/14/1002/12/14106735_413837609.shtml ][关于 己所不欲勿施于人 的反例]]
看问之后自己所获匪浅 原来很多自己认为很简单的道理或事情永远没有那么简单。文章里有不同的观点，果然一千个观众眼中有一千个哈姆雷特。
（这时候 自己走神了，不由自主想到 果然人生烦恼识字起啊 自己的观点抵抗不了别人的观点的时候 烦恼就开始了，如果 抵抗不了很多不同的观点 那就开始苦恼了 哈哈。
这是我自己的毛病啊 老爱走神，不知道别人怎么样。) 

  言归正传， 下面我引用了一些原话 来满足这个快餐时代。
#+BEGIN_QUOTE
 秉持「己所不欲，勿施於人」是件好事。但容易走進的誤區是：
「己所欲，施於人。」
 許多人非常怕的一句話，叫「我是爲了你好」。就是這麼來的。
#+END_QUOTE

#+BEGIN_QUOTE
这其实是一个如何判断他人感受的问题。用自己的感受（己所不欲）来判断是一种方式，但这种方式绝不是完全准确的，根本没有 @薛輝揚 说的「不受時空限制之特性」。
在大多数情况下「己所不欲勿施于人」没有出现问题是因为人们的感受、尤其是人们厌恶的东西很相似，另一个原因是人们通常不会钻牛角尖，只用「己所不欲，勿施于人」这一条准则行事。
#+END_QUOTE

#+BEGIN_QUOTE
這話背後是一種「推己及人」的態度，在邏輯上並不嚴謹。通過這話學會換位思考就很好，但別把它放大作為為人處事的原則。
一件事是否應該「施於人」，和自己究竟慾不慾沒有關係。該施的就是該施，判斷究竟該不該施就是很難。躲在「己所不欲，勿施於人」這話背後偷懶、逃避判斷，是該反對的。
#+END_QUOTE

#+BEGIN_QUOTE
康德《道德形而上学基础》（1785）杨云飞 译，邓晓芒 校
26页，注释：人们不要以为。“己所不欲，勿施于人”这种老生常谈在此可以用作准或原则，因为这句话只是从上述那个原则中推到出来的，尽管有各种限制；它决不可能是普遍法则，
因为它即不包含对自己的义务的根据，也不包含对他人的爱的义务之根据（因为有不少人会乐意同意，别人不应对他人行善，只要他可以免除对别人表示善行），
最后，也不包含相互之间应尽的义务制根据；因为罪犯会从这一根据出发对要惩罚他的法官提出争辩，等等。
#+END_QUOTE

 /呵呵 我迷失在这 各种观点中... 所有的东西一旦上升到哲学 就开始很难理解了/

总之开始这是一篇想写成批判的文章的。但最后总结，其实我们俩都有错误。都有认知偏差。这个结果比我想象的要差一点。但对我们的认知却有促进作用。

果然纸上得来终觉浅，希望自己以后能坚持多思考AND多反省AND多记录一些东西吧



